spring:
  application.name: bank-account-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:file:./data/bankdb;DB_CLOSE_DELAY=-1}

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:
    hibernate:
      # 'update' creates tables if they don't exist
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
logging:
    pattern:
        console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - [%X{traceId}] - %msg%n"
    level:
      org:
        springframework:
          security: DEBUG
          web: DEBUG

server:
  port: 8080
  servlet:
    context-path: /api/v1

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:792B4B6250655368566D597133743677397A24432646294A404D635166546A57}
      # Expiration time 24h
      expiration: 86400000
  external:
    url: ${APPLICATION_EXTERNAL_URL:https://httpbin.org/status}
    # in days
  retention: 90
  defaultPassword: password123